### PR TITLE
[WIP] feat(formats) : add possibility to convert to multiple formats

### LINKED ISSUE #42: webp export
Any change to add webp as an option? 
Ideally it would be nice to build something like 
```
<picture>
    <!--[if IE 9]><video style="display: none;"><![endif]-->
    <source type="image/webp" srcset="2700x1209/rocket-pods-mr-ben-01-2700x1209.webp 2700w, 
                    1800x806/rocket-pods-mr-ben-01-1800x806.webp 1800w, 
                    1536x1536/rocket-pods-mr-ben-01-1536x1536.webp 1536w, 
                    1024x1024/rocket-pods-mr-ben-01-1024x1024.webp 1024w, 
                    900x900/rocket-pods-mr-ben-01-900x900.webp 900w, 
                    600x600/rocket-pods-mr-ben-01-600x600.webp 600w" 
            sizes="100vw" />
    <source srcset="2700x1209/rocket-pods-mr-ben-01-2700x1209.jpg 2700w, 
                    1800x806/rocket-pods-mr-ben-01-1800x806.jpg 1800w, 
                    1536x1536/rocket-pods-mr-ben-01-1536x1536.jpg 1536w, 
                    1024x1024/rocket-pods-mr-ben-01-1024x1024.jpg 1024w, 
                    900x900/rocket-pods-mr-ben-01-900x900.jpg 900w, 
                    600x600/rocket-pods-mr-ben-01-600x600.jpg 600w" 
            sizes="100vw" />
    <!--[if IE 9]></video><![endif]-->
    <img class="rsImg" src="600x600/rocket-pods-mr-ben-01-600x600.jpg" alt="Visit MrBen" />
</picture>
```

### PR DESCRIPTION
**Pull request by ghetolay**
Add support to convert a source image into multiple formats. Also introducing `webp` as a valid format (only when using sharp).

This closes #42.

This is a work in progress, I just wrote the code and didn't even run it once, I'll finish it next week end.
Meanwhile we could discuss about new inputs/outputs, here is how I did it for the moment : 

## Inputs
- `format`: `webp` is now a valid format if sharp is used.
- new `formats` options taking an array of format. `format` should probably be deprecated.
  - Alternative: make `format` more flexible, accepts both single format and array of format.

- By convention the fallback and placeholder type are of the first format passed in.

## Outputs
- `srcsets`: array of srcset and mime types `[{srcset: string, mime: string}]`
- `imagesByMime`: array of images and mime type `[{images: [string]}, mime: string]`. I've named it that way temporarily and to avoid breaking change with current `images`.
- `srcset` and `images` contains the srcset and the image array of the first format.

### CODE REVIEW

**Comment by herrstucki** [comment]
Hey @ghetolay, that looks great! Thanks for the contribution!

Does the option to convert to multiple formats in one pass add that much value compared to importing the same image multiple times? I'm a little concerned about `imagesByMime` or changing the structure of `images`.

- The main reason for my concern is that depending on if `formats` is used, the output of the loader would change from a flat list of images to one grouped by mime type. The alternative would be to always group by mime type but I don't think that's very user-friendly in the single-format case.
- Is picking the first format in the list as the "main" top-level image is a good idea (shouldn't it be the last one?)?

These are just preliminary thoughts, I'm totally open to discussing this further. Maybe it would help if you could outline some examples of _how_ multiple formats will be used in an app.

Could you maybe separate adding support for webp as an option for `format` and multiple formats into different PRs? I think the first one we can merge right away (once there are tests) and the multi-format option needs a bit more discussion.

**Comment by ghetolay** [comment]
Importing same image multiple times will make the loader decode the image each time depending on the size and number of the images this could have a real impact.

We could get rid of `imagesByMime` and just append everything to `images` if you want. I'm not sure what's the use of that `images` property that's why I didn't know how to handle it. 
Which brings me to a new PR I may submit before this one. What do you think about adding the possibility to the user to generate the output ? 
I'm a bit concerned about the ouput because it's what's gonna stick on prod files, so I would like to tailor it to my needs and remove unused properties (especially big ones like `images`). 
We could add a new `generateOutput` option expecting a function easily. 

> Is picking the first format in the list as the "main" top-level image is a good idea (shouldn't it be the last one?)?

Well I went with first because you're already using first image to populate width/height property, I don't know which one makes more sense because in the end it depends on which order user will define formats and sizes.  

> Maybe it would help if you could outline some examples of how multiple formats will be used in an app.

My use case is to generate a `<picture>` dynamically, creating a `<source>` per mime type and an `` fallback. So the properties I'm interested in are `srcsets` and `src`.

> Could you maybe separate adding support for webp as an option for format and multiple formats into different PRs?

Yes totally, will do.

**Comment by StephanGerbeth** [comment]
Please integrate the webp support :)

**Comment by blowsie** [comment]
What work is outstanding, how can I help?

**Comment by strarsis** [comment]
Please merge! I need webp support.

**Comment by ivandokov** [comment]
@ghetolay can you please fix the conflict so this can get merged.
Or @herrstucki can you please take a look at this and probably re-create the PR as it may not be fixed by @ghetolay and be lost. This is a really useful PR and as you see there is a demand from other people to use it. Thanks.

**Comment by dscafati** [comment]
For those that are waiting for this change, I made similar changes to enable webp support on https://github.com/dscafati/responsive-loader . You have to run "yarn add dscafati/responsive-loader" to enable it (you can also use npm).
Your package.json will look like this:

`{
...
  "dependencies": {
...
    "responsive-loader": "dscafati/responsive-loader",
    "sharp": "^0.24.1"
...
  }
...
}
`

Notice that you also need an up-to-date version of the sharp dependency.

Then you can use `require()` or `import from` and include format=webp in the query string of the path you are importing

I only added the webp mime to the list of supported mime tipes, and registered the webp extension for these images. I didn't add any validation, e.g. if you are using jimp you won't see any warnging.

**Pull request closed without merging**
