### PR TITLE
Added webp support for the sharp adapter

### PR DESCRIPTION
**Pull request by dscafati**

### CODE REVIEW

**Comment by dscafati** [comment]
https://sharp.pixelplumbing.com/changelog#v0210---4supthsup-october-2018

**Comment by dscafati** [comment]
@herrstucki the tests are failing because the snapshots doesn't match. They don't match because the hashes that form the file name are different. Aren't they supposed to be expected?

**Comment by wbobeirne** [comment]
Would love to see this get in soon, this PR looks much cleaner than #100 to me.

---

I believe the hashes are supposed to be deterministic based on the file content, so you should run `yarn test -- -u` to update all of them with the new version of sharp which probably has minor, subtle differences. After that, the tests will pass.

I also think we should go up to sharp `v0.23.2`+, since that added support for node 13 which is going to go LTS in a couple of months, so it would be good to have in.

Last note, looks like your yarn removed all of the integrity hashes. You may want to upgrade yarn and re-run it to restore those.

**Comment by tgdn** [comment]
Hello all,

First thank you for the great work you do, this library is awesome!
I just wanted to know the state of this PR?

Thank you in advance,
Thomas

**Comment by dscafati** [comment]
@wbobeirne Thanks for the clarification, I updated the hashes knowing they won't change again and also updated the sharp version number. All tests are passing correctly on Travis.

@tgdn I think this PR is now ready to be merged

@herrstucki fyi

**Comment by strarsis** [comment]
It is necessary to either let some other user take over this repository or declare a new official fork.

**Comment by strarsis** [comment]
@dscafati: Issues in your forked repository are disabled. 😿 
I installed the [`responsive-loader-webp`](https://www.npmjs.com/package/responsive-loader-webp) package from npm but I get this error during build:
````
Module build failed: ModuleBuildError: Module build failed: TypeError: formats.map is not a function
    at Object.loader ([...]/node_modules/responsive-loader-webp/lib/index.js:50:23)
    at runLoaders ([...]/node_modules/webpack/lib/NormalModule.js:195:19)
    at [...]/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at [...]/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync ([...]/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders ([...]/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at iterateNormalLoaders ([...]/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at [...]/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync ([...]/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders ([...]/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> ([...]/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished ([...]/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:40:15)
    at [...]/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:77:9
    at [...]/node_modules/graceful-fs/graceful-fs.js:115:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

````

**Comment by dscafati** [comment]
@strarsis just to be sure, are you running `npm i responsive-loader-webp` or `npm i dscafati/responsive-loader`  ? And can you provide more context of where you see this error, npm version, etc.? I'll try to take a look soon

**Comment by strarsis** [comment]
@dscafati: `npm i responsive-loader-webp`.
But with `npm i dscafati/responsive-loader` the built files are missing.

**Comment by dscafati** [comment]
Hi @strarsis , the version I published to npm is one I did for testing hardcoding values on the compiled files because I needed it urgently. Now I published the current version to npm, it's responsive-loader-webp and the version is 1.2.0-beta.2 . Let me know if it doesn't work

**Comment by strarsis** [comment]
@dscafati: If you could add support for [`multiple formats`](https://github.com/herrstucki/responsive-loader/pull/58), this would be awesome. Currently, I have to use `responsive-loader` two times, the second time with `&format=webp`.

**Comment by dazuaz** [comment]
This was helpfull for me to keep the original package name:
```npm i <alias_name>@npm:<original_package_name>```
```npm i responsive-loader@npm:responsive-loader-webp@1.2.0-beta.2```

**Comment by strarsis** [comment]
We need an official fork or continuation of this project!

**Comment by dazuaz** [comment]
I have created a new repo that merges webp support and also updates all dependencies to latest
https://www.npmjs.com/package/responsive-images-loader

@strarsis please feel free to open a new issue there where we can discuss how to implement multiple formats

**Pull request merged**
